replicaCount: 1

image:
  repository: fatliverfreddy/cyphernetes-operator
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# At least one kind must be specified
managedKinds:
  - deployments.apps

extraPermissions:
  - kind: services
    verbs:
      - get
      - list
      - watch
  - kind: ingresses.networking.k8s.io
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  # - kind: deployments.apps
  #   verbs:
  #     - get
  #     - list
  #     - watch
  #     - create
  #     - update
  #     - patch
  #     - delete
  # - kind: services
  #   verbs:
  #     - get
  #     - list
  #     - watch
  #     - create
  #     - update
  #     - patch
  #     - delete
