replicaCount: 1

image:
  repository: fatliverfreddy/cyphernetes-operator
  pullPolicy: IfNotPresent
  tag: "v0.18.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# At least one kind must be specified.
# These are the kinds that dynamic operators created by this controller can manage.
managedKinds:
  # - exposeddeployments # For exposeddeployment operator
  - deployments.apps # For active/inactive ingress operator

# These are the permissions to run Cyphernetes queries by the dynamic operators created by this controller.
extraPermissions:
  # Example permissions for exposeddeployments operator
  # - kind: deployments.apps
  #   verbs:
  #     - get
  #     - list
  #     - watch
  #     - create
  #     - update
  #     - patch
  #     - delete
  # - kind: services
  #   verbs:
  #     - get
  #     - list
  #     - watch
  #     - create
  #     - update
  #     - patch
  #     - delete
  # Example permissions for ingresses active/inactive operator
  - kind: services
    verbs:
      - get
      - list
      - watch
  - kind: ingresses.networking.k8s.io
    verbs:
      - get
      - list
      - watch
      - update
      - patch
