// Code generated by goyacc -o pkg/parser/cyphernetes.go -p yy grammar/cyphernetes.y. DO NOT EDIT.

//line grammar/cyphernetes.y:2
package parser

import __yyfmt__ "fmt"

//line grammar/cyphernetes.y:2

import (
	"fmt"
	"log"
	"strconv"
	"strings"
)

func yyerror(s string) {
	fmt.Printf("Syntax error: %s\n", s)
}

func debugLog(v ...interface{}) {
	if LogLevel == "debug" {
		log.Println(v...)
	}
}

//line grammar/cyphernetes.y:22
type yySymType struct {
	yys                  int
	strVal               string
	jsonPath             string
	jsonPathList         []string
	nodePattern          *NodePattern
	clause               *Clause
	expression           *Expression
	matchClause          *MatchClause
	setClause            *SetClause
	deleteClause         *DeleteClause
	returnClause         *ReturnClause
	properties           *Properties
	jsonPathValue        *Property
	jsonPathValueList    []*Property
	keyValuePairs        []*KeyValuePair
	keyValuePair         *KeyValuePair
	value                interface{}
	relationship         *Relationship
	resourceProperties   *ResourceProperties
	nodeRelationshipList *NodeRelationshipList
	nodeIds              []string
}

const IDENT = 57346
const JSONPATH = 57347
const INT = 57348
const BOOLEAN = 57349
const STRING = 57350
const LPAREN = 57351
const RPAREN = 57352
const COLON = 57353
const MATCH = 57354
const SET = 57355
const DELETE = 57356
const RETURN = 57357
const EOF = 57358
const LBRACE = 57359
const RBRACE = 57360
const COMMA = 57361
const EQUALS = 57362
const REL_NOPROPS_RIGHT = 57363
const REL_NOPROPS_LEFT = 57364
const REL_NOPROPS_BOTH = 57365
const REL_NOPROPS_NONE = 57366
const REL_BEGINPROPS_LEFT = 57367
const REL_BEGINPROPS_NONE = 57368
const REL_ENDPROPS_RIGHT = 57369
const REL_ENDPROPS_NONE = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"JSONPATH",
	"INT",
	"BOOLEAN",
	"STRING",
	"LPAREN",
	"RPAREN",
	"COLON",
	"MATCH",
	"SET",
	"DELETE",
	"RETURN",
	"EOF",
	"LBRACE",
	"RBRACE",
	"COMMA",
	"EQUALS",
	"REL_NOPROPS_RIGHT",
	"REL_NOPROPS_LEFT",
	"REL_NOPROPS_BOTH",
	"REL_NOPROPS_NONE",
	"REL_BEGINPROPS_LEFT",
	"REL_BEGINPROPS_NONE",
	"REL_ENDPROPS_RIGHT",
	"REL_ENDPROPS_NONE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar/cyphernetes.y:273

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 77

var yyAct = [...]int8{
	47, 10, 64, 24, 20, 32, 52, 11, 28, 27,
	29, 26, 31, 30, 25, 34, 28, 27, 29, 26,
	31, 30, 37, 57, 56, 55, 54, 40, 66, 67,
	38, 36, 39, 35, 62, 16, 41, 42, 7, 14,
	13, 46, 3, 53, 8, 9, 7, 68, 44, 49,
	50, 48, 43, 12, 59, 60, 4, 65, 21, 45,
	18, 58, 15, 51, 33, 23, 22, 19, 17, 70,
	69, 61, 63, 6, 5, 2, 1,
}

var yyPact = [...]int16{
	30, -1000, 31, 44, 24, 23, 19, 55, 53, 61,
	-1000, -5, 60, -1000, -1000, -1, -1000, 14, -1000, 12,
	-1000, 2, 11, -1000, 44, 44, -1000, -1000, -1000, -1000,
	60, 60, 42, 37, -1000, 54, 53, 43, 59, -13,
	-1000, -2, -4, -1000, 57, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 44, 44, -1000, -1000, -1000, -1000, 17, -1000,
	-1000, -1000, 52, 10, -1000, 36, -1000, 52, 43, -1000,
	-1000,
}

var yyPgo = [...]int8{
	0, 76, 75, 74, 73, 56, 7, 72, 2, 0,
	71, 68, 3, 5, 1, 67, 4, 66,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 2, 3, 4, 17, 17,
	15, 15, 16, 14, 14, 14, 14, 14, 6, 5,
	11, 11, 12, 12, 12, 12, 12, 12, 12, 12,
	13, 13, 10, 7, 7, 8, 9, 9, 9,
}

var yyR2 = [...]int8{
	0, 3, 3, 4, 3, 2, 2, 2, 1, 3,
	1, 3, 3, 1, 3, 5, 5, 3, 3, 2,
	1, 3, 1, 1, 1, 1, 3, 3, 3, 3,
	3, 4, 3, 1, 3, 3, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, 12, -5, -3, -4, 15, 13, 14,
	-14, -6, 9, 16, 16, -5, 16, -11, 5, -15,
	-16, 5, -17, 4, -12, 19, 24, 22, 21, 23,
	26, 25, -13, 4, 16, 19, 19, 20, 19, -6,
	-14, -13, -13, 10, 11, 5, -16, -9, 8, 6,
	7, 4, 19, -12, 28, 27, 28, 27, 4, -14,
	-14, -10, 17, -7, -8, 5, 18, 19, 11, -8,
	-9,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 13, 0, 1, 2, 0, 4, 19, 20, 6,
	10, 0, 7, 8, 0, 0, 22, 23, 24, 25,
	0, 0, 0, 0, 3, 0, 0, 0, 0, 14,
	17, 0, 0, 18, 0, 21, 11, 12, 36, 37,
	38, 9, 0, 0, 26, 28, 27, 29, 30, 15,
	16, 31, 0, 0, 33, 0, 32, 0, 0, 34,
	35,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:79
		{
			result = &Expression{Clauses: []Clause{yyDollar[1].matchClause, yyDollar[2].returnClause}}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:82
		{
			result = &Expression{Clauses: []Clause{yyDollar[1].matchClause, yyDollar[2].setClause}}
		}
	case 3:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar/cyphernetes.y:85
		{
			result = &Expression{Clauses: []Clause{yyDollar[1].matchClause, yyDollar[2].setClause, yyDollar[3].returnClause}}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:88
		{
			result = &Expression{Clauses: []Clause{yyDollar[1].matchClause, yyDollar[2].deleteClause}}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar/cyphernetes.y:94
		{
			yyVAL.matchClause = &MatchClause{Nodes: yyDollar[2].nodeRelationshipList.Nodes, Relationships: yyDollar[2].nodeRelationshipList.Relationships}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar/cyphernetes.y:100
		{
			yyVAL.setClause = &SetClause{KeyValuePairs: yyDollar[2].keyValuePairs}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar/cyphernetes.y:106
		{
			yyVAL.deleteClause = &DeleteClause{NodeIds: yyDollar[2].nodeIds}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:112
		{
			yyVAL.nodeIds = []string{yyDollar[1].strVal}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:115
		{
			yyVAL.nodeIds = append(yyDollar[1].nodeIds, yyDollar[3].strVal)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:121
		{
			yyVAL.keyValuePairs = []*KeyValuePair{yyDollar[1].keyValuePair} // Start with one Property element
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:124
		{
			yyVAL.keyValuePairs = append(yyDollar[1].keyValuePairs, yyDollar[3].keyValuePair) // $1 and $3 are the left and right operands of COMMA
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:131
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyDollar[1].strVal, Value: yyDollar[3].value}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:137
		{
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         []*NodePattern{yyDollar[1].nodePattern},
				Relationships: []*Relationship{},
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:143
		{
			yyDollar[2].relationship.LeftNode = yyDollar[1].nodePattern
			yyDollar[2].relationship.RightNode = yyDollar[3].nodePattern
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         []*NodePattern{yyDollar[1].nodePattern, yyDollar[3].nodePattern},
				Relationships: []*Relationship{yyDollar[2].relationship},
			}
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar/cyphernetes.y:151
		{
			yyDollar[2].relationship.LeftNode = yyDollar[1].nodePattern
			yyDollar[2].relationship.RightNode = yyDollar[3].nodePattern
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyDollar[1].nodePattern, yyDollar[3].nodePattern}, yyDollar[5].nodeRelationshipList.Nodes...),
				Relationships: append([]*Relationship{yyDollar[2].relationship}, yyDollar[5].nodeRelationshipList.Relationships...),
			}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar/cyphernetes.y:159
		{
			yyDollar[2].relationship.LeftNode = yyDollar[1].nodePattern
			yyDollar[2].relationship.RightNode = yyDollar[3].nodePattern
			yyDollar[4].relationship.LeftNode = yyDollar[3].nodePattern
			yyDollar[4].relationship.RightNode = yyDollar[5].nodeRelationshipList.Nodes[0]
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyDollar[1].nodePattern, yyDollar[3].nodePattern}, yyDollar[5].nodeRelationshipList.Nodes...),
				Relationships: append([]*Relationship{yyDollar[2].relationship, yyDollar[4].relationship}, yyDollar[5].nodeRelationshipList.Relationships...),
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:169
		{
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyDollar[1].nodePattern}, yyDollar[3].nodeRelationshipList.Nodes...),
				Relationships: yyDollar[3].nodeRelationshipList.Relationships,
			}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:178
		{
			yyVAL.nodePattern = &NodePattern{ResourceProperties: yyDollar[2].resourceProperties}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar/cyphernetes.y:184
		{
			yyVAL.returnClause = &ReturnClause{JsonPaths: yyDollar[2].jsonPathList}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:190
		{
			yyVAL.jsonPathList = []string{yyDollar[1].strVal}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:193
		{
			yyVAL.jsonPathList = append(yyDollar[1].jsonPathList, yyDollar[3].strVal)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:199
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: None, LeftNode: nil, RightNode: nil}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:202
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Left, LeftNode: nil, RightNode: nil}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:205
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Right, LeftNode: nil, RightNode: nil}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:208
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Both, LeftNode: nil, RightNode: nil}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:211
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyDollar[2].resourceProperties, Direction: None, LeftNode: nil, RightNode: nil}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:214
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyDollar[2].resourceProperties, Direction: Left, LeftNode: nil, RightNode: nil}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:217
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyDollar[2].resourceProperties, Direction: Right, LeftNode: nil, RightNode: nil}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:220
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyDollar[2].resourceProperties, Direction: Both, LeftNode: nil, RightNode: nil}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:226
		{
			yyVAL.resourceProperties = &ResourceProperties{Name: yyDollar[1].strVal, Kind: yyDollar[3].strVal, Properties: nil}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar/cyphernetes.y:229
		{
			yyVAL.resourceProperties = &ResourceProperties{Name: yyDollar[1].strVal, Kind: yyDollar[3].strVal, Properties: yyDollar[4].properties}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:235
		{
			yyVAL.properties = &Properties{PropertyList: yyDollar[2].jsonPathValueList}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:241
		{
			yyVAL.jsonPathValueList = []*Property{yyDollar[1].jsonPathValue} // Start with one Property element
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:244
		{
			yyVAL.jsonPathValueList = append(yyDollar[1].jsonPathValueList, yyDollar[3].jsonPathValue) // $1 and $3 are the left and right operands of COMMA
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar/cyphernetes.y:250
		{
			yyVAL.jsonPathValue = &Property{Key: yyDollar[1].strVal, Value: yyDollar[3].value}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:256
		{
			yyVAL.value = strings.Trim(yyDollar[1].strVal, "\"")
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:259
		{
			// Parse the int from the string
			i, err := strconv.Atoi(yyDollar[1].strVal)
			if err != nil {
				// ... handle error
				panic(err)
			}
			yyVAL.value = i
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar/cyphernetes.y:268
		{
			// Parse the boolean from the string
			yyVAL.value = strings.ToUpper(yyDollar[1].strVal) == "TRUE"
		}
	}
	goto yystack /* stack new state and value */
}
