// Code generated by goyacc - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import (
	"fmt"
	"log"
	"strconv"
	"strings"
)

func yyerror(s string) {
	fmt.Printf("Syntax error: %s\n", s)
}

func debugLog(v ...interface{}) {
	if LogLevel == "debug" {
		log.Println(v...)
	}
}

type yySymType struct {
	yys                  int
	strVal               string
	jsonPath             string
	nodePattern          *NodePattern
	clause               *Clause
	expression           *Expression
	matchClause          *MatchClause
	setClause            *SetClause
	deleteClause         *DeleteClause
	createClause         *CreateClause
	returnClause         *ReturnClause
	returnItems          []*ReturnItem
	returnItem           *ReturnItem
	properties           *Properties
	jsonPathValue        *Property
	jsonPathValueList    []*Property
	keyValuePairs        []*KeyValuePair
	keyValuePair         *KeyValuePair
	value                interface{}
	relationship         *Relationship
	resourceProperties   *ResourceProperties
	nodeRelationshipList *NodeRelationshipList
	nodeIds              []string
	contexts             []string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault           = 57386
	yyEofCode           = 57344
	AS                  = 57366
	BOOLEAN             = 57349
	COLON               = 57354
	COMMA               = 57364
	CONTAINS            = 57382
	COUNT               = 57375
	CREATE              = 57359
	DELETE              = 57358
	EOF                 = 57361
	EQUALS              = 57365
	GREATER_THAN        = 57378
	GREATER_THAN_EQUALS = 57380
	IDENT               = 57346
	IN                  = 57384
	INT                 = 57348
	JSONDATA            = 57351
	JSONPATH            = 57347
	LBRACE              = 57362
	LESS_THAN           = 57379
	LESS_THAN_EQUALS    = 57381
	LPAREN              = 57352
	MATCH               = 57355
	NOT_EQUALS          = 57377
	NULL                = 57385
	RBRACE              = 57363
	REGEX_COMPARE       = 57383
	REL_BEGINPROPS_LEFT = 57371
	REL_BEGINPROPS_NONE = 57372
	REL_ENDPROPS_NONE   = 57374
	REL_ENDPROPS_RIGHT  = 57373
	REL_NOPROPS_BOTH    = 57369
	REL_NOPROPS_LEFT    = 57368
	REL_NOPROPS_NONE    = 57370
	REL_NOPROPS_RIGHT   = 57367
	RETURN              = 57360
	RPAREN              = 57353
	SET                 = 57357
	STRING              = 57350
	SUM                 = 57376
	WHERE               = 57356
	yyErrCode           = 57345

	yyMaxDepth = 200
	yyTabOfs   = -73
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57361: 0,  // EOF (52x)
		57364: 1,  // COMMA (41x)
		57360: 2,  // RETURN (34x)
		57359: 3,  // CREATE (31x)
		57358: 4,  // DELETE (26x)
		57357: 5,  // SET (26x)
		57344: 6,  // $end (17x)
		57352: 7,  // LPAREN (14x)
		57346: 8,  // IDENT (11x)
		57363: 9,  // RBRACE (11x)
		57351: 10, // JSONDATA (10x)
		57349: 11, // BOOLEAN (9x)
		57348: 12, // INT (9x)
		57347: 13, // JSONPATH (9x)
		57385: 14, // NULL (9x)
		57350: 15, // STRING (9x)
		57407: 16, // Value (9x)
		57403: 17, // ReturnClause (8x)
		57356: 18, // WHERE (8x)
		57398: 19, // NodePattern (6x)
		57374: 20, // REL_ENDPROPS_NONE (6x)
		57373: 21, // REL_ENDPROPS_RIGHT (6x)
		57353: 22, // RPAREN (6x)
		57355: 23, // MATCH (5x)
		57399: 24, // NodeRelationshipList (5x)
		57389: 25, // CreateClause (4x)
		57371: 26, // REL_BEGINPROPS_LEFT (4x)
		57372: 27, // REL_BEGINPROPS_NONE (4x)
		57369: 28, // REL_NOPROPS_BOTH (4x)
		57368: 29, // REL_NOPROPS_LEFT (4x)
		57370: 30, // REL_NOPROPS_NONE (4x)
		57367: 31, // REL_NOPROPS_RIGHT (4x)
		57366: 32, // AS (3x)
		57354: 33, // COLON (3x)
		57394: 34, // KeyValuePair (3x)
		57362: 35, // LBRACE (3x)
		57402: 36, // ResourceProperties (3x)
		57387: 37, // Context (2x)
		57375: 38, // COUNT (2x)
		57390: 39, // DeleteClause (2x)
		57392: 40, // JSONPathValue (2x)
		57395: 41, // KeyValuePairs (2x)
		57396: 42, // MatchClause (2x)
		57401: 43, // Relationship (2x)
		57404: 44, // ReturnItem (2x)
		57406: 45, // SetClause (2x)
		57376: 46, // SUM (2x)
		57382: 47, // CONTAINS (1x)
		57388: 48, // Contexts (1x)
		57365: 49, // EQUALS (1x)
		57391: 50, // Expression (1x)
		57378: 51, // GREATER_THAN (1x)
		57380: 52, // GREATER_THAN_EQUALS (1x)
		57384: 53, // IN (1x)
		57393: 54, // JSONPathValueList (1x)
		57379: 55, // LESS_THAN (1x)
		57381: 56, // LESS_THAN_EQUALS (1x)
		57397: 57, // NodeIds (1x)
		57377: 58, // NOT_EQUALS (1x)
		57400: 59, // Properties (1x)
		57383: 60, // REGEX_COMPARE (1x)
		57405: 61, // ReturnItems (1x)
		57386: 62, // $default (0x)
		57345: 63, // error (0x)
	}

	yySymNames = []string{
		"EOF",
		"COMMA",
		"RETURN",
		"CREATE",
		"DELETE",
		"SET",
		"$end",
		"LPAREN",
		"IDENT",
		"RBRACE",
		"JSONDATA",
		"BOOLEAN",
		"INT",
		"JSONPATH",
		"NULL",
		"STRING",
		"Value",
		"ReturnClause",
		"WHERE",
		"NodePattern",
		"REL_ENDPROPS_NONE",
		"REL_ENDPROPS_RIGHT",
		"RPAREN",
		"MATCH",
		"NodeRelationshipList",
		"CreateClause",
		"REL_BEGINPROPS_LEFT",
		"REL_BEGINPROPS_NONE",
		"REL_NOPROPS_BOTH",
		"REL_NOPROPS_LEFT",
		"REL_NOPROPS_NONE",
		"REL_NOPROPS_RIGHT",
		"AS",
		"COLON",
		"KeyValuePair",
		"LBRACE",
		"ResourceProperties",
		"Context",
		"COUNT",
		"DeleteClause",
		"JSONPathValue",
		"KeyValuePairs",
		"MatchClause",
		"Relationship",
		"ReturnItem",
		"SetClause",
		"SUM",
		"CONTAINS",
		"Contexts",
		"EQUALS",
		"Expression",
		"GREATER_THAN",
		"GREATER_THAN_EQUALS",
		"IN",
		"JSONPathValueList",
		"LESS_THAN",
		"LESS_THAN_EQUALS",
		"NodeIds",
		"NOT_EQUALS",
		"Properties",
		"REGEX_COMPARE",
		"ReturnItems",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {50, 3},
		2:  {50, 5},
		3:  {50, 3},
		4:  {50, 5},
		5:  {50, 4},
		6:  {50, 6},
		7:  {50, 3},
		8:  {50, 5},
		9:  {50, 2},
		10: {50, 4},
		11: {50, 3},
		12: {50, 5},
		13: {50, 3},
		14: {50, 5},
		15: {50, 4},
		16: {50, 6},
		17: {42, 2},
		18: {42, 4},
		19: {25, 2},
		20: {45, 2},
		21: {39, 2},
		22: {57, 1},
		23: {57, 3},
		24: {41, 1},
		25: {41, 3},
		26: {34, 3},
		27: {34, 3},
		28: {34, 3},
		29: {34, 3},
		30: {34, 3},
		31: {34, 3},
		32: {34, 3},
		33: {34, 3},
		34: {24, 1},
		35: {24, 3},
		36: {24, 5},
		37: {24, 5},
		38: {24, 3},
		39: {19, 3},
		40: {19, 3},
		41: {17, 2},
		42: {61, 1},
		43: {61, 3},
		44: {44, 1},
		45: {44, 3},
		46: {44, 4},
		47: {44, 4},
		48: {44, 6},
		49: {44, 6},
		50: {43, 1},
		51: {43, 1},
		52: {43, 1},
		53: {43, 1},
		54: {43, 3},
		55: {43, 3},
		56: {43, 3},
		57: {43, 3},
		58: {36, 3},
		59: {36, 4},
		60: {36, 5},
		61: {59, 3},
		62: {54, 1},
		63: {54, 3},
		64: {40, 3},
		65: {16, 1},
		66: {16, 1},
		67: {16, 1},
		68: {16, 1},
		69: {16, 1},
		70: {48, 1},
		71: {48, 3},
		72: {37, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [140][]uint16{
		// 0
		{3: 79, 23: 78, 25: 77, 42: 75, 50: 74, 53: 76},
		{6: 73},
		{2: 151, 79, 187, 186, 17: 201, 25: 204, 39: 203, 45: 202},
		{8: 174, 37: 173, 48: 172},
		{149, 2: 151, 17: 150},
		// 5
		{7: 82, 19: 81, 24: 126},
		{7: 82, 19: 81, 24: 80},
		{54, 2: 54},
		{39, 106, 39, 39, 39, 39, 18: 39, 26: 112, 111, 110, 108, 107, 109, 43: 105},
		{8: 84, 36: 83},
		// 10
		{22: 104},
		{22: 85, 33: 86},
		{33, 33, 33, 33, 33, 33, 18: 33, 26: 33, 33, 33, 33, 33, 33},
		{8: 87},
		{20: 15, 15, 15, 35: 89, 59: 88},
		// 15
		{20: 14, 14, 14},
		{10: 90, 13: 93, 40: 92, 54: 91},
		{20: 13, 13, 13},
		{1: 102, 9: 101},
		{1: 11, 9: 11},
		// 20
		{33: 94},
		{10: 99, 98, 97, 14: 100, 96, 95},
		{1: 9, 9: 9},
		{8, 8, 8, 8, 8, 8, 9: 8},
		{7, 7, 7, 7, 7, 7, 9: 7},
		// 25
		{6, 6, 6, 6, 6, 6, 9: 6},
		{5, 5, 5, 5, 5, 5, 9: 5},
		{4, 4, 4, 4, 4, 4, 9: 4},
		{20: 12, 12, 12},
		{13: 93, 40: 103},
		// 30
		{1: 10, 9: 10},
		{34, 34, 34, 34, 34, 34, 18: 34, 26: 34, 34, 34, 34, 34, 34},
		{7: 82, 19: 121},
		{7: 82, 19: 81, 24: 120},
		{7: 23},
		// 35
		{7: 22},
		{7: 21},
		{7: 20},
		{8: 114, 36: 117},
		{8: 114, 36: 113},
		// 40
		{20: 115, 116},
		{33: 86},
		{7: 18},
		{7: 16},
		{20: 118, 119},
		// 45
		{7: 19},
		{7: 17},
		{35, 2: 35, 35, 35, 35, 18: 35},
		{38, 122, 38, 38, 38, 38, 18: 38, 26: 112, 111, 110, 108, 107, 109, 43: 123},
		{7: 82, 19: 81, 24: 125},
		// 50
		{7: 82, 19: 81, 24: 124},
		{36, 2: 36, 36, 36, 36, 18: 36},
		{37, 2: 37, 37, 37, 37, 18: 37},
		{2: 56, 56, 56, 56, 18: 127},
		{13: 130, 34: 129, 41: 128},
		// 55
		{1: 147, 55, 55, 55, 55},
		{49, 49, 49, 49, 49, 49},
		{47: 137, 49: 131, 51: 133, 135, 55: 134, 136, 58: 132, 60: 138},
		{10: 99, 98, 97, 14: 100, 96, 146},
		{10: 99, 98, 97, 14: 100, 96, 145},
		// 60
		{10: 99, 98, 97, 14: 100, 96, 144},
		{10: 99, 98, 97, 14: 100, 96, 143},
		{10: 99, 98, 97, 14: 100, 96, 142},
		{10: 99, 98, 97, 14: 100, 96, 141},
		{10: 99, 98, 97, 14: 100, 96, 140},
		// 65
		{10: 99, 98, 97, 14: 100, 96, 139},
		{40, 40, 40, 40, 40, 40},
		{41, 41, 41, 41, 41, 41},
		{42, 42, 42, 42, 42, 42},
		{43, 43, 43, 43, 43, 43},
		// 70
		{44, 44, 44, 44, 44, 44},
		{45, 45, 45, 45, 45, 45},
		{46, 46, 46, 46, 46, 46},
		{47, 47, 47, 47, 47, 47},
		{13: 130, 34: 148},
		// 75
		{48, 48, 48, 48, 48, 48},
		{6: 64},
		{171},
		{13: 154, 38: 155, 44: 153, 46: 156, 61: 152},
		{32, 169},
		// 80
		{31, 31},
		{29, 29, 32: 167},
		{35: 162},
		{35: 157},
		{13: 158},
		// 85
		{9: 159},
		{26, 26, 32: 160},
		{8: 161},
		{24, 24},
		{13: 163},
		// 90
		{9: 164},
		{27, 27, 32: 165},
		{8: 166},
		{25, 25},
		{8: 168},
		// 95
		{28, 28},
		{13: 154, 38: 155, 44: 170, 46: 156},
		{30, 30},
		{6: 62},
		{1: 177, 3: 79, 23: 78, 25: 176, 42: 175},
		// 100
		{1: 3, 3: 3, 23: 3},
		{1: 1, 3: 1, 23: 1},
		{2: 151, 79, 187, 186, 17: 182, 25: 185, 39: 184, 45: 183},
		{179, 2: 151, 17: 180},
		{8: 174, 37: 178},
		// 105
		{1: 2, 3: 2, 23: 2},
		{6: 63},
		{181},
		{6: 61},
		{200},
		// 110
		{197, 2: 151, 17: 198},
		{196},
		{193, 2: 151, 17: 194},
		{13: 130, 34: 129, 41: 192},
		{8: 189, 57: 188},
		// 115
		{52, 190},
		{51, 51},
		{8: 191},
		{50, 50},
		{53, 147, 53},
		// 120
		{6: 59},
		{195},
		{6: 57},
		{6: 65},
		{6: 69},
		// 125
		{199},
		{6: 67},
		{6: 71},
		{212},
		{209, 2: 151, 17: 210},
		// 130
		{208},
		{205, 2: 151, 17: 206},
		{6: 60},
		{207},
		{6: 58},
		// 135
		{6: 66},
		{6: 70},
		{211},
		{6: 68},
		{6: 72},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 63

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].returnClause}}
		}
	case 2:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].returnClause}, Contexts: yyS[yypt-3].contexts}
		}
	case 3:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].setClause}}
		}
	case 4:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].setClause}, Contexts: yyS[yypt-3].contexts}
		}
	case 5:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-3].matchClause, yyS[yypt-2].setClause, yyS[yypt-1].returnClause}}
		}
	case 6:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-3].matchClause, yyS[yypt-2].setClause, yyS[yypt-1].returnClause}, Contexts: yyS[yypt-4].contexts}
		}
	case 7:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].deleteClause}}
		}
	case 8:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].deleteClause}, Contexts: yyS[yypt-3].contexts}
		}
	case 9:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-1].createClause}}
		}
	case 10:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-1].createClause}, Contexts: yyS[yypt-2].contexts}
		}
	case 11:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].createClause, yyS[yypt-1].returnClause}}
		}
	case 12:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].createClause, yyS[yypt-1].returnClause}, Contexts: yyS[yypt-3].contexts}
		}
	case 13:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].createClause}}
		}
	case 14:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-2].matchClause, yyS[yypt-1].createClause}, Contexts: yyS[yypt-3].contexts}
		}
	case 15:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-3].matchClause, yyS[yypt-2].createClause, yyS[yypt-1].returnClause}}
		}
	case 16:
		{
			result = &Expression{Clauses: []Clause{yyS[yypt-3].matchClause, yyS[yypt-2].createClause, yyS[yypt-1].returnClause}, Contexts: yyS[yypt-4].contexts}
		}
	case 17:
		{
			yyVAL.matchClause = &MatchClause{Nodes: yyS[yypt-0].nodeRelationshipList.Nodes, Relationships: yyS[yypt-0].nodeRelationshipList.Relationships, ExtraFilters: nil}
		}
	case 18:
		{
			yyVAL.matchClause = &MatchClause{Nodes: yyS[yypt-2].nodeRelationshipList.Nodes, Relationships: yyS[yypt-2].nodeRelationshipList.Relationships, ExtraFilters: yyS[yypt-0].keyValuePairs}
		}
	case 19:
		{
			yyVAL.createClause = &CreateClause{Nodes: yyS[yypt-0].nodeRelationshipList.Nodes, Relationships: yyS[yypt-0].nodeRelationshipList.Relationships}
		}
	case 20:
		{
			yyVAL.setClause = &SetClause{KeyValuePairs: yyS[yypt-0].keyValuePairs}
		}
	case 21:
		{
			yyVAL.deleteClause = &DeleteClause{NodeIds: yyS[yypt-0].nodeIds}
		}
	case 22:
		{
			yyVAL.nodeIds = []string{yyS[yypt-0].strVal}
		}
	case 23:
		{
			yyVAL.nodeIds = append(yyS[yypt-2].nodeIds, yyS[yypt-0].strVal)
		}
	case 24:
		{
			yyVAL.keyValuePairs = []*KeyValuePair{yyS[yypt-0].keyValuePair} // Start with one Property element
		}
	case 25:
		{
			yyVAL.keyValuePairs = append(yyS[yypt-2].keyValuePairs, yyS[yypt-0].keyValuePair) // $1 and $3 are the left and right operands of COMMA
		}
	case 26:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "EQUALS"} // ==
		}
	case 27:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "NOT_EQUALS"} // !=
		}
	case 28:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "GREATER_THAN"} // >
		}
	case 29:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "LESS_THAN"} // <
		}
	case 30:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "GREATER_THAN_EQUALS"} // >=
		}
	case 31:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "LESS_THAN_EQUALS"} // <=
		}
	case 32:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "CONTAINS"} // CONTAINS
		}
	case 33:
		{
			yyVAL.keyValuePair = &KeyValuePair{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value, Operator: "REGEX_COMPARE"} // =~
		}
	case 34:
		{
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         []*NodePattern{yyS[yypt-0].nodePattern},
				Relationships: []*Relationship{},
			}
		}
	case 35:
		{
			yyS[yypt-1].relationship.LeftNode = yyS[yypt-2].nodePattern
			yyS[yypt-1].relationship.RightNode = yyS[yypt-0].nodePattern
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         []*NodePattern{yyS[yypt-2].nodePattern, yyS[yypt-0].nodePattern},
				Relationships: []*Relationship{yyS[yypt-1].relationship},
			}
		}
	case 36:
		{
			yyS[yypt-3].relationship.LeftNode = yyS[yypt-4].nodePattern
			yyS[yypt-3].relationship.RightNode = yyS[yypt-2].nodePattern
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyS[yypt-4].nodePattern, yyS[yypt-2].nodePattern}, yyS[yypt-0].nodeRelationshipList.Nodes...),
				Relationships: append([]*Relationship{yyS[yypt-3].relationship}, yyS[yypt-0].nodeRelationshipList.Relationships...),
			}
		}
	case 37:
		{
			yyS[yypt-3].relationship.LeftNode = yyS[yypt-4].nodePattern
			yyS[yypt-3].relationship.RightNode = yyS[yypt-2].nodePattern
			yyS[yypt-1].relationship.LeftNode = yyS[yypt-2].nodePattern
			yyS[yypt-1].relationship.RightNode = yyS[yypt-0].nodeRelationshipList.Nodes[0]
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyS[yypt-4].nodePattern, yyS[yypt-2].nodePattern}, yyS[yypt-0].nodeRelationshipList.Nodes...),
				Relationships: append([]*Relationship{yyS[yypt-3].relationship, yyS[yypt-1].relationship}, yyS[yypt-0].nodeRelationshipList.Relationships...),
			}
		}
	case 38:
		{
			yyVAL.nodeRelationshipList = &NodeRelationshipList{
				Nodes:         append([]*NodePattern{yyS[yypt-2].nodePattern}, yyS[yypt-0].nodeRelationshipList.Nodes...),
				Relationships: yyS[yypt-0].nodeRelationshipList.Relationships,
			}
		}
	case 39:
		{
			yyVAL.nodePattern = &NodePattern{ResourceProperties: yyS[yypt-1].resourceProperties}
		}
	case 40:
		{
			yyVAL.nodePattern = &NodePattern{&ResourceProperties{Name: yyS[yypt-1].strVal, Kind: "", Properties: nil, JsonData: ""}}
		}
	case 41:
		{
			yyVAL.returnClause = &ReturnClause{Items: yyS[yypt-0].returnItems}
		}
	case 42:
		{
			yyVAL.returnItems = []*ReturnItem{yyS[yypt-0].returnItem}
		}
	case 43:
		{
			yyVAL.returnItems = append(yyS[yypt-2].returnItems, yyS[yypt-0].returnItem)
		}
	case 44:
		{
			yyVAL.returnItem = &ReturnItem{JsonPath: yyS[yypt-0].strVal}
		}
	case 45:
		{
			yyVAL.returnItem = &ReturnItem{JsonPath: yyS[yypt-2].strVal, Alias: yyS[yypt-0].strVal}
		}
	case 46:
		{
			yyVAL.returnItem = &ReturnItem{Aggregate: "COUNT", JsonPath: yyS[yypt-1].strVal}
		}
	case 47:
		{
			yyVAL.returnItem = &ReturnItem{Aggregate: "SUM", JsonPath: yyS[yypt-1].strVal}
		}
	case 48:
		{
			yyVAL.returnItem = &ReturnItem{Aggregate: "COUNT", JsonPath: yyS[yypt-3].strVal, Alias: yyS[yypt-0].strVal}
		}
	case 49:
		{
			yyVAL.returnItem = &ReturnItem{Aggregate: "SUM", JsonPath: yyS[yypt-3].strVal, Alias: yyS[yypt-0].strVal}
		}
	case 50:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: None, LeftNode: nil, RightNode: nil}
		}
	case 51:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Left, LeftNode: nil, RightNode: nil}
		}
	case 52:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Right, LeftNode: nil, RightNode: nil}
		}
	case 53:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: nil, Direction: Both, LeftNode: nil, RightNode: nil}
		}
	case 54:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyS[yypt-1].resourceProperties, Direction: None, LeftNode: nil, RightNode: nil}
		}
	case 55:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyS[yypt-1].resourceProperties, Direction: Left, LeftNode: nil, RightNode: nil}
		}
	case 56:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyS[yypt-1].resourceProperties, Direction: Right, LeftNode: nil, RightNode: nil}
		}
	case 57:
		{
			yyVAL.relationship = &Relationship{ResourceProperties: yyS[yypt-1].resourceProperties, Direction: Both, LeftNode: nil, RightNode: nil}
		}
	case 58:
		{
			yyVAL.resourceProperties = &ResourceProperties{Name: yyS[yypt-2].strVal, Kind: yyS[yypt-0].strVal, Properties: nil, JsonData: ""}
		}
	case 59:
		{
			yyVAL.resourceProperties = &ResourceProperties{Name: yyS[yypt-3].strVal, Kind: yyS[yypt-1].strVal, Properties: yyS[yypt-0].properties, JsonData: ""}
		}
	case 60:
		{
			yyVAL.resourceProperties = &ResourceProperties{Name: yyS[yypt-4].strVal, Kind: yyS[yypt-2].strVal, Properties: nil, JsonData: yyS[yypt-0].strVal}
		}
	case 61:
		{
			yyVAL.properties = &Properties{PropertyList: yyS[yypt-1].jsonPathValueList}
		}
	case 62:
		{
			yyVAL.jsonPathValueList = []*Property{yyS[yypt-0].jsonPathValue} // Start with one Property element
		}
	case 63:
		{
			yyVAL.jsonPathValueList = append(yyS[yypt-2].jsonPathValueList, yyS[yypt-0].jsonPathValue) // $1 and $3 are the left and right operands of COMMA
		}
	case 64:
		{
			yyVAL.jsonPathValue = &Property{Key: yyS[yypt-2].strVal, Value: yyS[yypt-0].value}
		}
	case 65:
		{
			yyVAL.value = strings.Trim(yyS[yypt-0].strVal, "\"")
		}
	case 66:
		{
			i, err := strconv.Atoi(yyS[yypt-0].strVal)
			if err != nil {
				panic(err)
			}
			yyVAL.value = i
		}
	case 67:
		{
			yyVAL.value = strings.ToUpper(yyS[yypt-0].strVal) == "TRUE"
		}
	case 68:
		{
			yyVAL.value = yyS[yypt-0].strVal
		}
	case 69:
		{
			yyVAL.value = nil
		}
	case 70:
		{
			yyVAL.contexts = []string{yyS[yypt-0].strVal}
		}
	case 71:
		{
			yyVAL.contexts = append(yyS[yypt-2].contexts, yyS[yypt-0].strVal)
		}
	case 72:
		{
			yyVAL.strVal = yyS[yypt-0].strVal
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
