apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposeddeployments.cyphernet.es
spec:
  group: cyphernet.es
  names:
    kind: ExposedDeployment
    listKind: ExposedDeploymentList
    plural: exposeddeployments
    singular: exposeddeployment
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
              required:
                - image