apiVersion: cyphernetes-operator.cyphernet.es/v1
kind: DynamicOperator
metadata:
  name: exposeddeployment-operator
spec:
  resourceKind: exposeddeployments
  namespace: default
  onCreate: |
    CREATE (d:Deployment {
      "metadata": {
        "name": "child-of-{{$.metadata.name}}",
        "labels": {
          "app": "child-of-{{$.metadata.name}}"
        },
      },
      "spec": {
        "selector": {
          "matchLabels": {
            "app": "child-of-{{$.metadata.name}}"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "child-of-{{$.metadata.name}}"
            }
          },
          "spec": {
            "containers": [
              {
                "name": "child-of-{{$.metadata.name}}",
                "image": "{{$.spec.image}}"
              }
            ]
          }
        }
      }
    });
    MATCH (d:Deployment {name: "child-of-{{$.metadata.name}}"})
    CREATE (d)->(s:Service);
  onDelete: |
    MATCH (d:Deployment {name: "child-of-{{$.metadata.name}}"})->(s:Service)
    DELETE d, s;
  finalizer: true