apiVersion: cyphernetes-operator.cyphernet.es/v1
kind: DynamicOperator
metadata:
  name: mycustomresource-operator
spec:
  resourceKind: mycustomresource
  namespace: default
  onCreate: |
    CREATE (deployment:Deployment {
      "metadata": {
        "name": "child-of-{{$.metadata.name}}",
        "labels": {
          "app": "child-of-{{$.metadata.name}}"
        },
        "ownerReferences": [
          {
            "apiVersion": "{{$.apiVersion}}",
            "kind": "{{$.kind}}",
            "name": "{{$.metadata.name}}",
            "uid": "{{$.metadata.uid}}"
          }
        ]
      },
      "spec": {
        "selector": {
          "matchLabels": {
            "app": "child-of-{{$.metadata.name}}"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "child-of-{{$.metadata.name}}"
            }
          },
          "spec": {
            "containers": [
              {
                "name": "child-of-{{$.metadata.name}}",
                "image": "{{$.spec.image}}"
              }
            ]
          }
        }
      }
    });
    MATCH (d:Deployment {name: "child-of-{{$.metadata.name}}"})
    CREATE (deployment)->(s:Service);
  onDelete: |
    MATCH (deployment:Deployment {name: "child-of-{{$.metadata.name}}"})->(s:Service)
    DELETE deployment, s;
  finalizer: true