apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cyphernetes-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cyphernetes-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: cyphernetes-operator-controller-manager
  namespace: cyphernetes-system
