apiVersion: v1
kind: Service
metadata:
  name: {{ include "cyphernetes-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "cyphernetes-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    control-plane: controller-manager