name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Setup Envtest
      uses: kubernetes-sigs/setup-kind@v0.7.0
      with:
        version: "v0.20.0"
    - name: Install Envtest
      run: |
        go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
        setup-envtest use 1.30.0
        echo "KUBEBUILDER_ASSETS=$(setup-envtest use 1.30.0 -p path)" >> $GITHUB_ENV
    - name: Setup KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.20.0"
    - name: Configure KinD
      run: |
        kind create cluster --name cyphernetes-test
        kubectl cluster-info --context kind-cyphernetes-test
    - name: Install goyacc
      run: go install golang.org/x/tools/cmd/goyacc@latest
    - name: Create the operator manifests
      run: make operator-manifests
    - name: Run tests
      run: make test
    - name: Run operator tests
      run: make operator-test
    - name: Build operator docker image
      run: make -C operator docker-build