name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Install goyacc
      run: go install golang.org/x/tools/cmd/goyacc@latest
    - name: Run tests
      run: make test
    - name: Run operator tests
      run: make operator-test
    - name: Build operator docker image
      run: make -C operator docker-build