name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Setup Kind
      uses: engineerd/setup-kind@v0.6.0
      with:
        version: "v0.24.0"
    - name: Install Envtest
      run: |
        go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
        setup-envtest use
        echo "KUBEBUILDER_ASSETS=$(setup-envtest use -p path)" >> $GITHUB_ENV
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Create a link to envtest in operator/bin
      run: mkdir -p ./operator/bin && ln -s $(which setup-envtest) ./operator/bin/setup-envtest
    - name: Create the operator manifests
      run: make operator-manifests
    - name: Run tests
      run: make test
    - name: Run web tests
      run: make web-test
    - name: Apply operator test CRDs
      run: kubectl apply -f ./operator/test/e2e/samples/crd-exposeddeployments.yaml
    - name: Run operator tests
      env:
        KUBEBUILDER_ASSETS: ${{ env.KUBEBUILDER_ASSETS }}
      run: make operator-test
    - name: Build operator docker image
      run: make -C operator docker-build
